/* NoX (NoC Simulator)
 *
 * Dept. of Computer Science & Engineering, Pennsylvania State University.
 * All Rights Reserved.
 *  
 * 1. License     
 * NoX is distributed free of charge for academic, educational, noncommercial 
 * research purposes as long as this notice in its entirety is preserved in
 * every file included in this package.
 * All commercial use of this program requires separate licence. Contact the
 * author for details.
 * 
 * 2. All the publications that used the simulation results generated by the 
 * NoX should notify the author of the publication information and put 
 * following reference.
 *
 *  http://www.cse.psu.edu/~dpark/nox/
 * 
 * 3. Modification of the source code is permitted and encouraged as long as 
 * it follows the terms described in this copyright notice.
 *
 * 4. The author is not responsible for any problems caused by possible errors
 * of the NoX package. Therefore, users should verify the simulation result
 * before using it in their publication.
 *
 * Dept. of Computer Science & Engineering, Pennsylvania State University.
 * Contact: dpark@cse.psu.edu 
 * 
 * 6. If problems are found with the NoX package, please send an email to the
 * author for discussion and correction.

 */

/* Update History
 *
 * Jan. 31, 2006  Version 1.0 released by Dongkook Park 
 *
 */


#ifndef LINK_H
#define LINK_H

extern mbox_t link_buf[MAX_NODES][MAX_PC-MAX_NIC_PC][MAX_VC];
void link_stage(); // This stage handles data transfer through the link.
void link_stage2(); // This stage handles data transfer through the link.
void link_stage3(); // This stage handles data transfer through the link.
void link_stage4(); // This stage handles data transfer through the link.
void link_stage5(); // This stage handles data transfer through the link.
void link_stage6(); // This stage handles data transfer through the link.
void link_stage7(); // This stage handles data transfer through the link.

#endif
